### ISSUE TITLE
JavaScript source code

### ISSUE THREAD

**Issue by AlirewzaBa** [AlirewzaBa/DevRouteFinder#3]
### Problem
Encountering an unexpected behavior in the JavaScript source code. While implementing certain functions in the file "script.js," the expected output is not being generated.

### Expected Outcome
Expecting the functions in the JavaScript file to perform the intended operations and generate the correct output based on the implementation.

### Additional Details
- The issue might be related to compatibility or syntax errors.
- Checked for console errors or warnings, but none were reported.
- Any specific error messages or logs encountered during execution would be helpful for further investigation.

**Comment by ho3einrp** [comment]
### Steps to Reproduce
1. Access the "script.js" file located in the "scripts" directory.
2. Implement the specific functions or modifications.
3. Execute the script or run the application where the JavaScript code is integrated.
